# Generated by Django 4.2 on 2025-09-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='institution',
            name='video_url',
            field=models.URLField(blank=True, help_text='MP4 link or YouTube embed link'),
        ),
    ]
