# Generated by Django 4.2 on 2025-08-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='description',
        ),
        migrations.RemoveField(
            model_name='country',
            name='flag_image_url',
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='flags/'),
        ),
        migrations.AddField(
            model_name='country',
            name='flag_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
